config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence:true
  validates :content, length:{in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show,:edit,:update,:destroy]
  def index
    @blogs = Blog.all
  end
  def new
    @blog = Blog.new
  end
  def create
    @blog = Blog.new(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice:"記事を作成しました！"
      else
        render :new
      end
    end
  end
  def show
  end
  def edit
  end
  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice:"記事を編集しました！"
    else
      render :edit
    end
  end
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:'記事を削除しました'
  end
  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end
  private
  def blog_params
    params.require(:blog).permit(:title,:content)
  end
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model:@blog, url: choose_new_or_edit, local:true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_message">
      <h2><%= @blog.errors.count %>件のエラーがあります</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %><br>
    <%= form.text_field :content %>
  </div>
  <%= form.submit "作成する" %>
<% end %>
<%= link_to "記事一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で投稿します</h3>
<%= form_with(model: @blog,local: true)do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル : <%= @blog.title %></p>
  <p>本文 : <%= @blog.content %></p>
  <%= form.submit "登録する" %>
  <%= form.submit "戻る", name:'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>投稿を編集</h1>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>投稿一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>
</table>
<div class="container">
  <div class="row">
    <% @blogs.each do |blog| %>
    <div class="col-md-3 card card-body m-1">
      <div class="">
        <h4><%= blog.title %></h4>
      </div>
      <div class="">
        <%= blog.content %>
      </div>
      <div class="container">
        <div class="row">
          <span class="col-md-3">
            <%= link_to 'show', blog_path(blog.id),class:"btn btn-primary btn-sm m-1" %>
          </span>
          <span class="col-md-3">
            <%= link_to 'edit', edit_blog_path(blog.id) ,class:"btn btn-secondary m-1 btn-sm"%>
          </span>
          <span class="col-md-3">
            <%= link_to 'delete', blog_path(blog.id),class:"btn btn-warning m-1 btn-sm", method: :delete %>
          </span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= link_to '新しくブログを作成する', new_blog_path %>

app/views/blogs/new.html.erb
<h1>新規投稿</h1>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>
<p><%= @blog.content %></p>
<%= link_to '記事一覧', blogs_path %>
<%= link_to '編集',edit_blog_path(@blog.id) %>
<%= link_to '削除',blog_path(@blog.id), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>